### ISSUE TITLE
Publish a 0.11.2 release

### ISSUE THREAD

**Issue by cpu** [rustls/rcgen#156]
I think it's a good time to cut a `0.11.2` release - I've done a scan of the contents of `main` since the last tag and don't believe anything consists of a breaking API change (but it would be helpful for someone to verify that line of thinking w.r.t the new CRL support types). This would also let a few Rustls projects remove `git` pins they're carrying for rcgen w/ CRL support.

The immediate changes I have in mind for addressing a few outstanding issues in the issue tracker are likely to require breaking changes (e.g. because they'll change what extensions are included in a CSR in a way that might break assumptions downstream code has made based on previous API contracts).

**Comment by est31** [comment]
@cpu we can cut a new release, sure. I will try to take a look this week. Regarding the changelog, previously I wouldn't mention myself as the author of some change when listing it in CHANGELOG.md, now with multiple contributors, I wonder if we should keep it that way, extend it to everyone from the `rustls` org, or always mention the contributor? The issue is, it's more work to mention the contributor on each bullet point, so personally I'm leaning towards the extension option but I'm open to hear opinions on that.

**Comment by est31** [comment]
(we can also completely stop mentioning the contributor, I started doing this to call out people's great contributions)

**Comment by cpu** [comment]
> we can cut a new release, sure. I will try to take a look this week.

Thanks!

@est31 Would it be helpful if I made a PR updating the CHANGELOG.md in `main` with some proposed release notes or would you prefer to do that yourself at release-time?

FWIW we've moved away from maintaining an explicit changelog in favour of using GitHub Releases each detailing their own changelog in the other Rustls repos. If you prefer the in-repo approach it isn't a big sticking point to me, but I do find the downstream Dependabot updates folks get render more helpfully w/ GitHub releases.

> I usually like to call out contributors who are not part of the maintainer team, so it would seem fair game to leave out @cpu and me as contributors.

This sounds fine to me :+1: 

> I like to mention all team members in the GitHub Release notes somewhere so that GitHub gets correct metadata for who contributed towards the release.

I think the [process we have documented](https://github.com/rustls/rustls/blob/main/RELEASING.md#after-making-a-release) makes this pretty easy. I would be in favour of trying to match that process as much as possible to avoid needing to page in/out different instructions per-repo.

**Comment by est31** [comment]
Update: sorry that I didn't get to it last week, also this week looks pretty unlikely I'm going to have time. Will try to do it next week however!

In general, I'm not a fan of only using github's release note feature, because those downloaded ones don't arrive at users via "git clone", but the users have to use github's website. Dependabot is an argument, maybe there is some way to auto-fill these from CHANGELOG.md.

**Comment by cpu** [comment]
> Would it be helpful if I made a PR updating the CHANGELOG.md in main with some proposed release notes or would you prefer to do that yourself at release-time?

I didn't hear back on this, so here's a CHANGELOG update to take or to leave: https://github.com/rustls/rcgen/pull/159
