### ISSUE TITLE
serialize_der() regenerates the certificate

### ISSUE THREAD

**Issue by jbg** [rustls/rcgen#62]
I am using rcgen to generate a certificate, then I'm sharing the fingerprint of the certificate with a peer, and then I'm using a library to communicate with that peer. The library requires me to provide the certificate & private key in PEM format.

I've been debugging for a while why the fingerprint I generate, like this:

```rust
let fingerprint = ring::digest::digest(&ring::digest::SHA256, &cert.serialize_der()?);
```

... does not match the fingerprint the peer expects to receive, nor the fingerprint OpenSSL reports when I supply it with the PEM-encoded certificate obtained with `serialize_pem()`.

After reading the discussion in #28, and looking at the code, I think I understand what's going on — `serialize_der()` and `serialize_pem()` are not actually just serializing; they are in fact *generating* the certificate each time they are called, so the random components are different between the DER serialization and the PEM serialization.

Ideally the certificate would be generated when the `Certificate` struct is created, so that it can be repeatedly serialized — perhaps into different formats — without regenerating it each time.

If that's not possible, the functions should either be renamed or at least the mis-naming documented clearly to save the time of anyone else who encounters this.

Right now, `from_params()` is documented as "Generates a new certificate" and `serialize_der()` is documented as "Serializes the certificate to the binary DER format", when in reality `from_params()` just stores the params (and does keygen if needed), and `serialize_der()` etc actually do the certificate generation.

**Comment by jeffparsons** [comment]
For the record, I recently got bitten by this while tinkering with certificate generation for tests. I was trying to figure out why there was a difference between serializing a certificate to PEM and serializing to DER. It turns out my client was ending up with one certificate and the server was ending up with another -- just because I was accidentally regenerating it, not because I was mishandling the DER formatted cert.

**Comment by est31** [comment]
> I guess there need to be two steps: one step letting you choose how to sign something. And the result of that can then be exported in DER or in PEM format.

To expand on this, my proposal would be to remove `serialize(_der)(_with_signer)` etc functions in favour of `serialize(_with_signer)` functions that return a `SerializedCertificate` (name to be bikeshedded). Then `SerializedCertificate` has `export_pem` and `export_der` functions or something like that. Also gets rid of the combinatorial explosion problem.

**Comment by cpu** [comment]
I'm not sure about adding a third layer like that. I think the OP and I both agree on the idea that `Certificate` should do what the name implies and represent a constructed certificate. I think it should hold the `der` bytes for a full signed certificate in addition to the `CertificateParams` and `KeyPair`. 

What about an API where: 

* `CertificateParams` are constructed much like they are now.
* `Certificate` gains a `der` field to hold a signed serialized certificate, and `der()` and `pem()` fn's for returning those bytes in the correct format.
* `Certificate::generate_self_signed(params: CertificateParams) -> Result<Self>` creates a self-signed `Certificate` from `CertificateParams`, generating the `Certificate` keypair if not specified in `params`. 
* `Certificate::generate(params: CertificateParams, issuer: &Certificate) -> Result<Self>` creates a certificate from `CertificateParams` that's signed by the `issuer`.
* `Certificate::generate_csr(csr: CertificateSigningRequest, issuer: &Certificate) -> Result<Self>` creates a certificate from the CSR `CertificateParams` that's signed by the `issuer`
* We remove `Certificate::from_params` and `serialize_(der|pem)[with_signer]`, and we remove `CertificateSigningRequest::serialize_(der|pem)[with_signer]`. I think the private key serialization fns on `Certificate` can remain as-is.

**Comment by est31** [comment]
I actually like your approach better (outside of naming and some details).

> We remove `Certificate::from_params`

a function like that is needed for importing of existing certificates. We could for example rename it to `import_from_der` and `import_from_pem`.

**Comment by cpu** [comment]
> a function like that is needed for importing of existing certificates. We could for example rename it to import_from_der and import_from_pem.

Good point. Having `Certificate::from_der(der: &[u8], key_pair: KeyPair)` and the same for PEM seems reasonable :+1: We would remove the `CertificateParams::from_ca_cert_pem` and `CertificateParams::from_ca_cert_der` in that case.

**Comment by cpu** [comment]
I started working on the proposed API last night and I like the direction but wasn't able to implement the idea as described end-to-end.

> Certificate::generate_csr(csr: CertificateSigningRequest, issuer: &Certificate) -> Result<Self> creates a certificate from the CSR CertificateParams that's signed by the issuer

One roadblock here: this isn't tenable with the `Certificate` holding `KeyPair` since the `CertificateSigningRequest` only has public key data.

IME it's more common to separate key generation and certificate generation. I think the `Certificate` type holding a private key is a little bit confusing. It means something that would otherwise be public data contains a secret (and so has to have a `Zeroize` impl and be handled carefully), and it introduces this asymmetry where in one case we want to generate a certificate without holding the subject's private key.

Perhaps `Certificate::generate_self_signed`, `Certificate::generate`, `Certificate::from_der` should be adapted to return `Result<(Certificate, PrivateKey)>` and `Certificate::generate_csr` would return just `Result<Certificate>`. In the case where the input `CertificateParams` specified a `KeyPair`, we can pass it through to the result. In the case where the params specify `None` we return the generated `KeyPair` along with the certificate.

**Comment by djc** [comment]
> Perhaps `Certificate::generate_self_signed`, `Certificate::generate`, `Certificate::from_der` should be adapted to return `Result<(Certificate, PrivateKey)>` and `Certificate::generate_csr` would return just `Result<Certificate>`. In the case where the input `CertificateParams` specified a `KeyPair`, we can pass it through to the result. In the case where the params specify `None` we return the generated `KeyPair` along with the certificate.

This sounds good to me (does `generate_csr()` yield a `Certificate` type today -- feels like that should be a distinct type?).

**Comment by cpu** [comment]
> (does generate_csr() yield a Certificate type today -- feels like that should be a distinct type?)

The equivalent API today is `CertificateSigningRequest::serialize_der_with_signer` and `CertificateSigningRequest::serialize_pem_with_signer`. They yield DER/PEM directly, not a `Certificate` representation, which is how they've side-stepped this problem.

**Comment by djc** [comment]
Ahh, so the difference is in `serialize_*_with_signer()` -> certificate vs `serialize_request_*` -> CSR.

**Comment by cpu** [comment]
> The last remaining change I wanted to do was try and harmonize the "from scratch" CertificateSigningRequest creation to match the new API, e.g. something like CertificateSigningRequest::generate(params: CertificateParams, key_pair: KeyPair)

This ends up being fairly tricky if we want to support all of the existing use cases because `CertificateParams` isn't `Clone` (mostly due to potentially holding private key material that itself isn't `Clone`). I've tried a few potential rearrangements but haven't arrived at something that seems workable. I might punt on this part and open a PR with the rest of the work since it seems more straight forward and would resolve the immediate issue.

**Comment by est31** [comment]
Some ideas to impl `Clone`: one can put the private key material into an `Arc` or implement it manually by serializing, then deserializing again (and panicking if that doesn't work).

**Comment by cpu** [comment]
I'm not going to have time to invest in continuing the API refactor beyond the certificate issuance API in the near future so I've cleaned up my WIP branch for review: https://github.com/rustls/rcgen/pull/205

The certificate issuance API is the most important w.r.t to the user confusion we see and so I think it makes sense to fix that without blocking on improvements to `CertificateSigningRequest`.

If folks disagree I'm happy to cede my branch to someone that has more time to push the remaining parts forward.
