### ISSUE TITLE
Make ring optional

### ISSUE THREAD

**Issue by tomleavy** [rustls/rcgen#74]
It would be nice to take advantage of the serialization part of the library without being tied specifically to ring. I believe `RemoteKeypair` could be leveraged to provide your own implementation of signing (perhaps with the Openssl crate)?

**Comment by est31** [comment]
That's an interesting proposal. I've thought about adding optional support for the rust crypto crates so you can choose between them and ring. I'm not sure about the review side of things though.

Openssl, at least the CLI, provides facilities to generate certificates as well, so I'm not sure why one wants to use it with `rcgen` instead of using it directly. What is your use case for this specific set up?

**Comment by tomleavy** [comment]
What I'm trying to do is have my code port to many systems / crypto libraries as possible while sharing as much as they can. One thing I want to be able to do is sign using WebCrypto API in the browser so I don't need any additional crypto library dependencies, the OpenSSL thing was just an example.

**Comment by djc** [comment]
While `RemoteKeyPair` works for signing, there's a still a bunch more stuff that would need work. For example, there's a decent amount of SHA256 going on outside the scope of signing itself.

**Comment by est31** [comment]
@tomleavy I see, that makes sense.

**Comment by iamjpotts** [comment]
`ring` also has a non-trivial license.

**Comment by est31** [comment]
cc https://github.com/rustls/rustls/issues/521, https://github.com/rustls/rustls/pull/1184

**Comment by cpu** [comment]
> cc https://github.com/rustls/rustls/issues/521, https://github.com/rustls/rustls/pull/1184

Also under consideration for `rustls/webpki`: https://github.com/rustls/webpki/issues/130

**Comment by cpu** [comment]
As of https://github.com/rustls/rcgen/commit/acec387ce1baf26f1be5b373c926d0195c831136 it's possible to build rcgen with [aws-lc-rs](https://github.com/aws/aws-lc-rs) instead of *ring* using `--no-default-features --features=aws_lc_rs`.

Being able to use an arbitrary cryptographic library will require more foundational work, closer to Rustls [crypto provider](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html) struct and associated traits. I suspect that's closer to what the OP wanted, so I think we should leave this issue open despite the fact that *ring* is technically now an optional dependency as the title of the issue requests.

**Comment by tomleavy** [comment]
I'm good to close this based on aws-lc-rs ... my original goal was to build in additional x509 support for mls-rs which is also an AWS project and has bindings for aws-lc-rs

**Comment by est31** [comment]
Okay, closing as per #201. Thanks, everyone!
